### PR TITLE
Added ru lang

### PR DESCRIPTION
**Pull request by hide-me**

### CODE REVIEW

**Comment by dignajar** [comment]
Hi @hide-me 
Can you help me with the translation for this plugin, https://github.com/bludit/plugins-repository/tree/master/items/yandex-metrica

Also here, https://github.com/bludit-plugins/yandex-metrica/tree/master/languages

Thank you

**Comment by hide-me** [comment]
This plugin already perfectly translated by author.
I've only tiny recommendation: title of plugin usually should translate, cuz title of plugin show short name of task, which would be solved by it. (title of theme is abstract and name like "Rebecca" just symbol of design spirit)

**Comment by hide-me** [comment]
Or u mean translation to Ukranian? 😃

**Comment by hide-me** [comment]
This plugin, alredy translated to Russian 👍

**Pull request merged**
