### PR TITLE
Added two new plugins, a scss and a minjs compiler. 

### PR DESCRIPTION
**Pull request by Scribilicious**
I added to new plugins:
- SCSS Compiler (a Sass / SCSS compiler)
- MinJS Compiler (a JS compiler / shrinker / minifier)

I also updated the version for Crop and Debug. Fixed some typos and added a clear cache button for the Crop plugin.

Enjoy & Thanks!

### CODE REVIEW

**Comment by clickwork-git** [comment]
Thank you very much!

**Comment by Scribilicious** [comment]
Hummm somehow it doesn't like my json, the Plugin page says:

Warning: Trying to access array offset on value of type bool in /www/plugins.bludit.com/html/home.php on line 21

The only difference I could find is an extra enter at the end of the json...

**Comment by clickwork-git** [comment]
"author_username" has to be "mrbot". ;-)

**Comment by Scribilicious** [comment]
Oh, my bad... Thanks for fixing it :)

**Pull request merged**
