### PR TITLE
Add Simple Stats Plus to Bludit Plugins Repository

### PR DESCRIPTION
**Pull request by BlakesHeaven**
Hi, @dignajar,
Following your suggestion, please have a look at these two files and commit them to your repository so others can benefit from the enhanced 'Simple Stats Plus' plugin should they wish.

If there is anything amiss, please advise.
Thank you.

### CODE REVIEW

**Comment by dignajar** [comment]
Great!
You can add some image / screenshot if you want to enhancement like I did in TimemachineX https://github.com/bludit/plugins-repository/tree/master/items/timemachine-x

**Comment by BlakesHeaven** [comment]
Hi @Dignajar, Do you mean "screenshot.png"?
It's already there.
Actually, I could not see it listed in Bludit Plugins, until I got to the very bottom, but it's  missing name and all details. When I click download all I see is my image 🤔😕
Did I do something wrong?

**Comment by BlakesHeaven** [comment]
Mmm, is it that comma at the end?

**Comment by BlakesHeaven** [comment]
Yep, it was - my bad 😳
I've now validated `metadata.json` and created a fresh pull request to remove the comma.

**Pull request merged**
