### PR TITLE
Fixed & Improved almost all plugins descriptions translations

### PR DESCRIPTION
**Pull request by hide-me**
1. Fixed & Improved almost all Russian translations
2. Extended a few descriptions in English
3. Fixed file style:

- Many spacebars --> Tab
- Dots in the ends of strings
- Deleted double spacebars in strings

Etc

### CODE REVIEW

**Comment by clickwork-git** [comment]
There are some conflicts. I will have a look at it tomorrow.

**Comment by hide-me** [comment]
Sure, thank you!

**Comment by clickwork-git** [comment]
I think it's better if you have a look at it, because I do not know which is the final version in Russian.

**Comment by hide-me** [comment]
Actually, this is the point of huge commit. I improved translatons. 

Conflicts exist because, I also improved style of json files. So, now, all of them has pretty similar style.

**Comment by clickwork-git** [comment]
There were still conflicts I had to solve. I hope everything works now.

Thank you very much for your great contribution!

**Pull request merged**
